INSERT INTO series (title, author_id, subgenre_id) VALUES ('series 1',1,1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ('series 2',2,2);
INSERT INTO subgenres (name) VALUES ('sub 1');
INSERT INTO subgenres (name) VALUES ('sub 2');
INSERT INTO books (title, year, series_id) VALUES ('book 1', 2001,1);
INSERT INTO books (title, year, series_id) VALUES ('book 2', 2011,1);
INSERT INTO books (title, year, series_id) VALUES ('book 3', 2014,2);
INSERT INTO books (title, year, series_id) VALUES ('book 4', 2008,2);
INSERT INTO books (title, year, series_id) VALUES ('book 5', 2009,1);
INSERT INTO books (title, year, series_id) VALUES ('book 6', 2003,1);
INSERT INTO authors (name) VALUES ('auth 1');
INSERT INTO authors (name) VALUES ('auth 2');
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 1','hey','human',1,1);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 2','hey','human',1,1);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 3','hey','human',2,2);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 4','hey','human',1,1);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 5','hey','human',1,1);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 6','hey','human',2,2);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 7','hey','human',2,2);
INSERT INTO characters (name, motto, species,author_id,series_id) VALUES ('char 8','hey','human',1,1);
INSERT INTO character_books (character_id, book_id) VALUES (1,1);
INSERT INTO character_books (character_id, book_id) VALUES (2,1);
INSERT INTO character_books (character_id, book_id) VALUES (3,1);
INSERT INTO character_books (character_id, book_id) VALUES (4,1);
INSERT INTO character_books (character_id, book_id) VALUES (5,1);
INSERT INTO character_books (character_id, book_id) VALUES (6,1);
INSERT INTO character_books (character_id, book_id) VALUES (7,1);
INSERT INTO character_books (character_id, book_id) VALUES (8,1);
INSERT INTO character_books (character_id, book_id) VALUES (1,2);
INSERT INTO character_books (character_id, book_id) VALUES (2,2);
INSERT INTO character_books (character_id, book_id) VALUES (3,2);
INSERT INTO character_books (character_id, book_id) VALUES (4,2);
INSERT INTO character_books (character_id, book_id) VALUES (5,2);
INSERT INTO character_books (character_id, book_id) VALUES (6,2);
INSERT INTO character_books (character_id, book_id) VALUES (7,2);
INSERT INTO character_books (character_id, book_id) VALUES (8,2);